2024-01-23 11:29:21,676 - INFO - [(STATUS) file opened: True]
2024-01-23 11:29:21,677 - ERROR - [(STATUS) [custom_exception]  File is empty, expected [size > 0], but found size to be: [0]
]
Traceback (most recent call last):
  File "hw2.py", line 665, in main
    timeList = createTimeList(input_file=filename)
  File "hw2.py", line 392, in createTimeList
    raise EmptyFileError(file_size=os.stat(input_file).st_size)
EmptyFileError: [DEFAULT]
Stack (most recent call last):
  File "hw2.py", line 684, in <module>
    main(filename)
  File "hw2.py", line 672, in main
    handle_custom_ab_derived_exceptions(custom_exception)
  File "hw2.py", line 633, in handle_custom_ab_derived_exceptions
    stack_info=True) if LOG else None
2024-01-23 11:29:21,678 - INFO - [(STATUS): garbo collector stats [{'collections': 22, 'collected': 99, 'uncollectable': 0}, {'collections': 2, 'collected': 0, 'uncollectable': 0}, {'collections': 1, 'collected': 0, 'uncollectable': 0}]]
